kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: video-tool-app
  namespace: dev
  selfLink: /apis/build.openshift.io/v1/namespaces/dev/buildconfigs/video-tool-app
  uid: 07973a03-2969-4991-b31f-5759080d4667
  resourceVersion: '127956466'
  creationTimestamp: '2020-05-08T06:40:08Z'
  labels:
    build: video-tool-app
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
spec:
  resources:
    limits:
      cpu: "1000m"
      memory: "1000Mi"
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'video-tool-app:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'nginx:mainline-alpine'
  postCommit: {}
  source:
    type: Binary
    binary: {}
  triggers:
    - type: GitHub
      github:
        secret: _cwKiL4-V73ENohD0UsV
    - type: Generic
      generic:
        secret: qRVr1RrXbr8QzbXwyE7x
  runPolicy: Serial
status:
  lastVersion: 1
