apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: ivid.datacollection-video-tool-app-develop-integration
  name: ivid.datacollection-video-tool-app-develop-integration
spec:
  resources:
    limits:
      cpu: '1000m'
      memory: '1000Mi'
  source:
    git:
      ref: master
      uri: https://github.com/ivid-123/demoapp.git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  triggers:
    - github:
        secret: secret
      type: GitHub
    - generic:
        secret: secret
      type: Generic
    - bitbucket:
        secret: secret
      type: Bitbucket
